version: '3.9'

services:
    postgres:
        image: postgres:17-alpine
        container_name: postgres-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - '5433:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - nike-network

    stripe-cli:
        image: stripe/stripe-cli:latest
        container_name: stripe-cli
        restart: unless-stopped
        command: listen --forward-to host.docker.internal:3000/api/stripe --skip-verify --log-level info
        environment:
            STRIPE_API_KEY: ${STRIPE_SECRET_KEY}
            STRIPE_DEVICE_NAME: nike-ecommerce-dev
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - postgres
        networks:
            - nike-network

networks:
    nike-network:
        driver: bridge

volumes:
    postgres_data:
        driver: local
